services:
  app:
    image: rust:1.82.0-alpine3.20
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh
    # 学習用のためコンテナで対話的に利用したい
    stdin_open: true 
    tty: true
